import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import MainNav from 'components/mainNav.tsx'
import Header from 'components/header.tsx'
import Footer from 'components/footer.tsx'
import Extra from 'components/extracomponent.tsx'
import { useEffect } from 'react'
import { useRouter } from 'next/router'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    
  return (
    <>
      <Head>
        <title>Trading application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.header}><Header/></div>
        <div className={styles.nav}><MainNav/></div>
        <div><Extra/></div>
        <div className={styles.footer} id="footer"><Footer/></div>

      </main>
    </>
  )
}