import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { Inter } from 'next/font/google'
import MainNav from '../organisms/mainNav.tsx'
import Header from '../organisms/header.tsx'
import Footer from '../organisms/footer.tsx'


const inter = Inter({ subsets: ['latin'] })

export default function Error(){
    return (
        <>
        <Head>
          <title>Error-Page does not exist</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        
        <main className={`${styles.main} ${inter.className}`}>
          <div className={styles.container}>
            <div className={styles.header}><Header/></div>
            <div className={styles.content}>
             <div>
                <h1 className='text-xl font-bold'>Error 404: Page does not exist</h1>
             </div>
            </div>
            <div className={styles.footer} id="footer"><Footer/></div>
          </div>
  
        </main>  
        <div className={styles.nav}><MainNav/></div>

      </>
    );
}